---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homer-local-assets-volume
  labels:
    directory: assets
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local
  local:
    path: /mnt/sda/homer/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master-rspi4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homer-local-assets-claim
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      directory: assets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  labels:
    app: homer
spec:
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
        name: homer
    spec:
      containers:
      - name: homer
        image: b4bz/homer:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: homer-local-assets-volume
          mountPath: "/www/assets"
      volumes:
      - name: homer-local-assets-volume
        persistentVolumeClaim:
          claimName: homer-local-assets-claim
---
apiVersion: v1
kind: Service
metadata:
  name: homer
spec:
  selector:
    app: homer
  ports:
  - port: 80
    targetPort: 8080
    name: homer-home
  externalIPs:
  - 10.0.0.100